### PR TITLE
Added a simple entrypoint

### PR DESCRIPTION
**Pull request by LightAndLight**
Request for comments on the module structure.

Also, do you think there is value in a "runAppWithQuit" function?

### CODE REVIEW

**Comment by dalaing** [comment]
I think if we're going to add `runAppForever`, we probably also want `runAppWithQuit`.

I'm not quite sure about the module structure, but only because we're likely to end up with a module that does this sort of thing per backend library, and so we might want to shoot for a `Reflex.Server.XYZ.Run` for the various values of `XYZ`.

I was actually thinking of changing the naming scheme to `Reflex.Backend.XYZ` anyhow, and then we could probably have `Reflex.Backend.XYZ.Server` (and `Reflex.Backend.XYZ.Client` if that is appropriate for things like websockets and servant).  What do you think?

**Comment by LightAndLight** [comment]
I haven't spent enough time in the ecosystem to have an opinion on the module names

**Comment by dalaing** [comment]
I've updated the module names now - if you change Reflex.Server.Warp to Reflex.Backend.Warp, I'll happily merge this in.

**Comment by LightAndLight** [comment]
It seems that I deleted my fork, so here's the new and updated PR from a local branch https://github.com/qfpl/reflex-backend-wai/pull/5

**Pull request closed without merging**
